// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faytlsrwiszkvakznkux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZheXRsc3J3aXN6a3Zha3pua3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjY4NDMsImV4cCI6MjA1OTIwMjg0M30.JCh9ieS52VN3MI-dwQLT8Es--MufTOvJIDLztxXsTqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);